### ISSUE TITLE
Module is broken when it comes to fresh installations...

### ISSUE THREAD

**Issue by rbargerhuff** [backdrop-contrib/paragraphs#132]
The issue my colleague and I just discovered is that Paragraphs is broken on fresh installations.

With our Drupal 7 installation, we did not use the `entitycache` module. With the migration of Backdrop and the use of the latest version of the `Paragraphs `module, we have encountered a scenario where Paragraphs module will NOT create the tables needed, in particular the table `cache_entity_paragraphs_item`

The code as it currently sits in `paragraphs.module`

_paragraphs.module 1594:_

```
if (module_exists('entitycache') && !db_table_exists('cache_entity_paragraphs_item')) {
    backdrop_load('module', 'entitycache');
    $cache_schema = backdrop_get_schema_unprocessed('system', 'cache');
    $cache_schema['description'] = 'Cache table used to store paragraphs_item entity records.';
    db_create_table('cache_entity_paragraphs_item', $cache_schema);
 }
```

This code is never executed because `entitycache` is part of Backdrop core.

Because the codebase forces entity cache to TRUE:

_paragraphs.module 155:_

`$return['paragraphs_item']['entity cache'] = TRUE;`

 This results in the following error:
 
 ```
$ bee cc all
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table &#039;ds306.cache_entity_paragraphs_item&#039; doesn&#039;t exist: TRUNCATE {cache_entity_paragraphs_item} ; Array
(
)
 in backdrop_flush_all_caches() (line 8599 of /var/www/bargerhuff/ds305/webroot/core/includes/common.inc).
```

**Comment by argiepiano** [comment]
You must be using version 1.1.0 of Paragraphs. Please check.

Because of a bug with the Backdrop CMS module portal the [Paragraphs version listed here](https://backdropcms.org/project/paragraphs)  is wrong. The current version 1.2.0-beta must be be manually [downloaded from here ](https://github.com/backdrop-contrib/paragraphs/releases/tag/1.x-1.2.0-beta1) 

I'm not a maintainer of Paragraph, but this issue has been reported in the past. @laryn - perhaps you or @bugfolder can manually edit the Backdrop CMS record that points to the wrong version?

**Comment by laryn** [comment]
@rbargerhuff I've released 1.x-1.2.0 today, in case the `beta` was scaring you off. Thanks @argiepiano for helping figure out the issue here.

**Comment by rbargerhuff** [comment]
@argiepiano @laryn Thank you very much! I didn't see your comments and I appreciate how quickly you responded. I am juggling a lot of work right now and did not notice.

We were using 1.20-beta1 when I first reported that issue. Upgrading to 1.20 addressed the issue and I have confirmed the fix.

Cheers to you both!
