### ISSUE TITLE
Is Paragraphs module supported? If yes, then which version is good to use?

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/paragraphs#133]
The `/admin/reports/updates` page on my setup gives scary warning:

![Screen Shot 2022-04-14 at 10 53 05 AM](https://user-images.githubusercontent.com/56604405/163427482-d12b764c-950e-464c-a4a0-9a7c5e0031cc.png)

So is the module is supported? Which version is recommended to use?

**Comment by argiepiano** [comment]
Uh oh. That's most likely a setting in the Backdrop module portal. @bugfolder? @laryn?

**Comment by bugfolder** [comment]
The current recommended release is 1.x-1.1.0 ("recommended" because that's the highest-numbered version that doesn't have development extra tags like "beta1"). It's currently marked as not supported, presumably because there are versions of 1.2.0-something. 

I've marked the recommended release 1.x-1.1.0 as supported; please check whether it's showing up properly in the updates page.

Since there have been 1.2.0-something releases since 2021-10-21, and people are being urged to use a 1.2.x version, I think it would be appropriate for @laryn to release a 1.2.0 version (no development suffix), and then, IIUC, that will become the recommended release and will also be displayed in the updates page.

**Comment by bugfolder** [comment]
Relevant issue: https://github.com/backdrop-ops/backdropcms.org/issues/905.

**Comment by laryn** [comment]
Thanks all. Since we've gone through two alphas and a beta at this point I also feel okay about releasing the current status as a more formal version. Done today.
