### ISSUE TITLE
Database update issue after Paragraphs module update

### ISSUE THREAD

**Issue by neessen** [backdrop-contrib/paragraphs#74]
I am having a strange problem on one site using the Paragraphs module.
After updating from version 1.x-1.0.1 to 1.x-1.1.0, I am not able to apply the database changes due to the following error:

`Some of the pending updates cannot be applied because their dependencies were not met`

After some debugging I got this error: 

`paragraphs module can not be updated. Its schema version is 7101. Updates up to and including 7103 have been removed in this release. In order to update paragraphs module, you will first need to upgrade to the last version in which these updates were available.`

However I have updated this module on two other sites without any issues. 

I reverted the changes, and started over, and checked that there are no missing updates needed to be applied in update.php prior to making this update. 
I was able to update Backdrop Core 1.17.1 to 1.17.3 and Entity Plus module without any problems, on this site, and on the two other sites as well. It is only the Paragraphs module which is causing problems on this site. Any idea what might cause this issue?

**Comment by laryn** [comment]
@neessen That is interesting because there is no `7101` in the Drupal version (at least not anymore!).

https://git.drupalcode.org/project/paragraphs/-/blob/7.x-1.x/paragraphs.install#L171-183

That said, the earliest versions of this port did not handle the schema versions correctly. Are you comfortable making a slight edit in the `.install` file and trying again (on a dev copy ideally)? Find this line:

https://github.com/backdrop-contrib/paragraphs/blob/1.x-1.x/paragraphs.install#L151

And try changing the `7102` to `7101`, then running database updates again.

**Comment by neessen** [comment]
Hey @laryn 
Thanks for the reply. 
Tried the above and the updates were installed succesfully after changing `7102` to `7101`, so it looks like that was the issue :)

**Comment by laryn** [comment]
Great -- thanks for following up!
